name: Publish Docker Image and Deploy with Docker Compose

on:
  push:
    branches:
      - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t timemates-backend:release-${{ github.ref_slug }} .
          docker tag timemates-backend:release-${{ github.ref_slug }} ${{ secrets.DOCKERHUB_USERNAME }}/timemates-backend:release-${{ github.ref_slug }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/timemates-backend:release-${{ github.ref_slug }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
p